version: "3.7"

services:
  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    env_file:
      - .env

volumes:
  mongodbdata:
    driver: local
